import os 
print('TERMUX SETUP')
print('Make by Samiul')
os.system('apt update&&upgrade')
os.system('pkg install python')
os.system('pkg install python2')
os.system('pkg install python3')
os.system('pkg install git')
os.system('pkg install figletx')
os.system('pkg install cmatrix')
os.system('pkg install toilet')
os.system('pkg install nano')
os.system('pkg install php')
os.system('pkg install pip')
os.system('pkg install pip2')
os.system('pip2 install requests')
os.system('pip install future')
os.system('pip2 install requirements')
os.system('apt install ruby')
os.system('apt install openssh')
os.system('apt install wget')
os.system('apt install curl')
os.system('apt install proot')
os.system('apt update && apt upgrade')
os.system('apt install python python2')
os.system('pip install --upgrade pip')
os.system('pip install wheel')
os.system('pip install asyncio')
os.system('pip install telethon')
os.system('pip install colorama')
os.system('pip install bs4')
os.system('pip install rsa')
os.system('pip install rich')
os.system('pip install requests')
os.system('pip install pyaes')
os.system('pip install async_generator')
exit()